version: "3.8"

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: adt-redis
    command: redis-server --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
    networks:
      - mynetwork
  
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: adt-backend
    env_file:
      - .env
    networks:
      - mynetwork
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: adt-nginx
    env_file:
      - .env
    networks:
      - mynetwork
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_PORT}
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/nginx.conf.template
    command: /bin/bash -c "envsubst < /nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - backend
      - redis

networks:
  mynetwork: