version: "3.8"

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: adt-redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - mynetwork
  
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: adt-backend
    env_file:
      - .env
    networks:
      - mynetwork
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: adt-nginx
    env_file:
      - .env
    networks:
      - mynetwork
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
      - redis

networks:
  mynetwork: