version: "3.8"

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    container_name: adt-redis
    ports:
      - 6379:6379
    networks:
      - mynetwork
  
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: adt-backend
    ports:
      - 8080:8080
    networks:
      - mynetwork
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: adt-nginx
    networks:
      - mynetwork
    ports:
      - 80:8089
    depends_on:
      - backend
      - redis


networks:
  mynetwork: